### ISSUE TITLE
Mechanism for remembering URL and/or login credentials 

### ISSUE THREAD

**Issue by zrthxn** [FNNDSC/chrs#1]
It'd be really helpful (from the perspective of someone testing the API) if the CLI can remember login details or maybe store a login token either in the system's environment or (securely) in a file. An ideal example would be Github's CLI `gh`.

So maybe you can run something like a login command
```bash
$ chrs login
> Your CUBE URI: http://localhost:8000/api/v1/
> Username: chris
> Password: *****
Attempting login... Saved token.
```

And then you'd be able to run your other commands without writing the credentials each time
```bash
$ find data_dir/ -type f | chrs upload {} > /dev/null
Uploading 10 files..........done.
```

**Comment by jennydaman** [comment]
I agree. `chrs login` is next on the roadmap (that I have in my mind).

The behavior I want to achieve will be the same here: https://github.com/FNNDSC/caw#logging-in

Here is what I would like to see:

1. use CLI flags `chrs --username chris --password chris1234 upload ...`
2. env vars `CHRIS_USERNAME=chris CHRIS_PASSWORD=chris1234 chrs upload ...`
3. `chrs login ...; chrs upload...`

Having done this before, know of a few mistakes which to avoid such as this: https://github.com/FNNDSC/caw/issues/11

**Comment by jennydaman** [comment]
(Unimportant: `chrs login` was actually item 3 on my roadmap, but I'm changing the order now!)
https://github.com/FNNDSC/chrs/blob/58712682b1b6bd7727f43c7c4d954ab2518c441b/README.md?plain=1#L87

**Comment by jennydaman** [comment]
5fa8f58517f587366a9e47f52140fe5784f6e23e
