### ISSUE TITLE
Create account

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/chrs#15]
`chrs login` should accept optional flags `--create` (bool) and `--email EMAIL` which, when used together, creates an account before logging in.

**Comment by lumuchris256** [comment]
@jennydaman i would like to take my spin on this

**Comment by jennydaman** [comment]
The functionality to create a user account is already implemented:

https://github.com/FNNDSC/chrs/blob/8f36480935e7298fb94f9a9bf4357f73d81cfda1/chris/src/auth.rs#L124-L147

To implement the propsoed feature, you would simply need to add the CLI options `--create` and `--email` here, and then pass those along to the helper function.

https://github.com/FNNDSC/chrs/blob/8f36480935e7298fb94f9a9bf4357f73d81cfda1/chrs/src/main.rs#L69-L78
