### ISSUE TITLE
Login with token

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/chrs#19]
allow `chrs login` to accept a token instead of password --- then maybe we can implement the feature in OpenShift where from the UI you can copy a login command with a token in it.

Ref: https://github.com/FNNDSC/ChRIS_ui/issues/404

**Comment by Prakashh21** [comment]
Hey @jennydaman I wanna try this , please assgin this to me !

**Comment by jennydaman** [comment]
Happy to offer guidance, just ping me on Matrix. Ideally we would want to support a use case like

```shell
chrs --address https://cube.chrisproject.org/api/v1/ --token abcdefg login

# or alternatively, for security paranoid people
chrs --address https://cube.chrisproject.org/api/v1/ --token-stdin <<< "abcdefg"
```

**Comment by Prakashh21** [comment]
@jennydaman  ya I would be needing your guidance on this one .. I'm new to rust also I would also need your opinion on this https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/381
